using PdfSharp.Drawing;
using PdfSharp.Fonts;
using PdfSharp.Pdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;

namespace BookSmart.Objects.Functions {
    public class PDFGenerator {
        public static void GenerateOrderReport(UserObj U) {
            GlobalFontSettings.UseWindowsFontsUnderWindows = true;
            using (PdfDocument document = new PdfDocument()) {
                document.Info.Title = "Order History Report";

                PdfPage page = document.AddPage();
                XGraphics gfx = XGraphics.FromPdfPage(page);
                XFont titleFont = new XFont("Arial", 18, XFontStyleEx.Bold);
                XFont boldFont = new XFont("Arial", 10, XFontStyleEx.Bold);
                XFont regularFont = new XFont("Arial", 10, XFontStyleEx.Bold);

                double y = 40;

                void CheckForNewPage() {
                    if (y > page.Height - 60) {
                        page = document.AddPage();
                        gfx = XGraphics.FromPdfPage(page);
                        y = 40;
                    }
                }

                gfx.DrawString("Order History Report", titleFont, XBrushes.Black, new XRect(0, y, page.Width, 30), XStringFormats.TopCenter);
                y += 40;

                gfx.DrawString("This is a report generated by BookSmart Shop featuring your order history for the last 3 months.", regularFont, XBrushes.Black, new XRect(0, y, page.Width, 20), XStringFormats.TopCenter);
                y += 30;

                gfx.DrawString($"Customer: {U.FirstName} {U.LastName}", regularFont, XBrushes.Black, new XPoint(40, y));
                y += 20;

                gfx.DrawString($"Date: {DateTime.Now:yyyy-MM-dd}", regularFont, XBrushes.Black, new XPoint(40, y));
                y += 30;

                gfx.DrawString("ID", boldFont, XBrushes.Black, new XPoint(40, y));
                gfx.DrawString("Date", boldFont, XBrushes.Black, new XPoint(80, y));
                gfx.DrawString("Status", boldFont, XBrushes.Black, new XPoint(150, y));
                gfx.DrawString("Total", boldFont, XBrushes.Black, new XPoint(220, y));
                gfx.DrawString("Items", boldFont, XBrushes.Black, new XPoint(280, y));
                y += 20;

                List<OrderObj> orders = U.getThreeMonthsOrders();
                foreach (OrderObj o in orders) {
                    gfx.DrawString(o.ID.ToString(), regularFont, XBrushes.Black, new XPoint(40, y));
                    gfx.DrawString(o.OrderDate.ToString("yyyy-MM-dd"), regularFont, XBrushes.Black, new XPoint(80, y));
                    gfx.DrawString(o.Status, regularFont, XBrushes.Black, new XPoint(150, y));

                    foreach (OrderItem item in o.getItems()) {
                        gfx.DrawString($"${item.Book.Price:N2}", regularFont, XBrushes.Black, new XPoint(220, y));
                        gfx.DrawString($"{item.Book.Title} (x{item.Amount})", regularFont, XBrushes.Black, new XPoint(280, y));
                        y += 12;
                    }

                    gfx.DrawString($"${o.getTotalCost():N2}", regularFont, XBrushes.Black, new XPoint(220, y));
                    gfx.DrawString($"Total", regularFont, XBrushes.Black, new XPoint(280, y));
                    y += 20;
                    CheckForNewPage();
                }

                y += 30;

                gfx.DrawString("BookSmart Shop", boldFont, XBrushes.Black, new XPoint(40, y));
                y += 15;

                gfx.DrawString("123 Labourdonnais St, Port-Louis, Mauritius", regularFont, XBrushes.Black, new XPoint(40, y));
                y += 15;

                gfx.DrawString("Phone: +230 5123 4567 | Email: support@booksmart.com", regularFont, XBrushes.Black, new XPoint(40, y));

                using (MemoryStream ms = new MemoryStream()) {
                    document.Save(ms, false);
                    byte[] pdfBytes = ms.ToArray();

                    HttpResponse response = HttpContext.Current.Response;
                    response.Clear();
                    response.ContentType = "application/pdf";
                    response.AddHeader("Content-Disposition", "attachment; filename=OrderReport.pdf");
                    response.OutputStream.Write(pdfBytes, 0, pdfBytes.Length);
                    response.Flush();
                    response.End();
                }
            }
        }
    }
}















